# Generated by Django 3.2.9 on 2021-12-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_relation_s_t_m'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relation_s_t_m',
            table='relation Student Teacher Model',
        ),
    ]
