# Generated by Django 3.2.9 on 2021-12-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_student_module'),
        ('module', '0005_remove_module_teacher'),
        ('teacher', '0003_alter_relation_s_t_m_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relation_S_T_M',
            new_name='relation_G_T_M',
        ),
    ]
