# Generated by Django 3.2.9 on 2021-12-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_student_module'),
        ('module', '0005_remove_module_teacher'),
        ('teacher', '0004_rename_relation_s_t_m_relation_g_t_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation_H_T_M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.homework')),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'relation homework Teacher Model',
            },
        ),
    ]
