# Generated by Django 3.2.9 on 2021-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20211215_1243'),
        ('module', '0005_remove_module_teacher'),
        ('teacher', '0005_relation_h_t_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_h_t_m',
            name='homework',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.homework'),
        ),
        migrations.AlterField(
            model_name='relation_h_t_m',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AlterField(
            model_name='relation_h_t_m',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
