# Generated by Django 3.2.9 on 2021-12-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_homework_order'),
        ('module', '0005_remove_module_teacher'),
        ('teacher', '0006_auto_20211215_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_g_t_m',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup'),
        ),
        migrations.AlterField(
            model_name='relation_g_t_m',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AlterField(
            model_name='relation_g_t_m',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
