# Generated by Django 3.2.9 on 2021-12-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_homework_student'),
        ('module', '0006_session_module'),
        ('teacher', '0007_auto_20211215_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='modules',
            field=models.ManyToManyField(blank=True, to='module.Module'),
        ),
        migrations.AlterField(
            model_name='relation_h_t_m',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.homework'),
        ),
    ]
