# Generated by Django 3.2.9 on 2021-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('bithdate', models.DateTimeField(null=True)),
                ('photo', models.ImageField(upload_to='image/student')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('state', models.CharField(choices=[('nouveau', 'nouveau'), ('redoublant', 'redoublant'), ('derogataire', 'derogataire')], max_length=150, null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
