# Generated by Django 3.2.9 on 2021-11-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Group  name')),
                ('mail_Group', models.CharField(max_length=15, null=True, verbose_name='Group email')),
                ('level', models.CharField(choices=[('level_1', 'level 1'), ('level_2', 'level 2')], max_length=25, null=True, verbose_name='Group Level')),
            ],
            options={
                'db_table': 'StudentGroup',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=150, null=True)),
                ('firstname', models.CharField(max_length=150, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='image/student')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('state', models.CharField(choices=[('nouveau', 'nouveau'), ('redoublant', 'redoublant'), ('derogataire', 'derogataire')], max_length=150, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Homework title')),
                ('launch_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(null=True, verbose_name='Homework deadline')),
                ('description', models.TextField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('ended', 'ended'), ('untended', 'untended')], max_length=15, null=True)),
                ('group', models.ManyToManyField(to='student.StudentGroup', verbose_name='Student homeworks')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module', verbose_name='Homework module')),
                ('students', models.ManyToManyField(to='student.Student', verbose_name='Student homeworks')),
            ],
            options={
                'db_table': 'Students_groups_homework',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Absent Date')),
                ('justification', models.TextField(max_length=250, null=True, verbose_name='Absent justification')),
                ('reason', models.CharField(choices=[('different type', 'different type'), ('other type', 'other type')], max_length=15, null=True, verbose_name='Reason of absence')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.session', verbose_name='Absent Session')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Absent Student')),
            ],
            options={
                'db_table': 'Student_absence',
            },
        ),
    ]
