# Generated by Django 3.2.9 on 2021-12-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='modulee',
            field=models.ManyToManyField(to='module.Module'),
        ),
    ]
