# Generated by Django 3.2.9 on 2021-11-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ManyToManyField(to='student.StudentGroup', verbose_name='Student homeworks'),
        ),
    ]
