# Generated by Django 3.2.9 on 2021-11-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='firstname',
        ),
    ]
