# Generated by Django 3.2.9 on 2021-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_homework_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=150),
        ),
    ]
