# Generated by Django 3.2.9 on 2021-12-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_modulee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='modulee',
            new_name='module',
        ),
    ]
