# Generated by Django 3.2.9 on 2021-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_modulee_student_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ManyToManyField(null=True, to='student.StudentGroup', verbose_name='Student homeworks'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(null=True, to='student.Student', verbose_name='Student homeworks'),
        ),
    ]
