# Generated by Django 3.2.9 on 2021-11-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_username_student_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='username',
        ),
    ]
