# Generated by Django 3.2.9 on 2021-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211213_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ManyToManyField(null=True, to='student.StudentGroup', verbose_name='Student homeworks group'),
        ),
    ]
