# Generated by Django 3.2.9 on 2021-11-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_firstname_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bithdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='firstname',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(max_length=250, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'Absence',
            },
        ),
    ]
