# Generated by Django 3.2.9 on 2021-12-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_homework_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='homeworks',
            field=models.ManyToManyField(null=True, to='student.HomeWork', verbose_name='Student homeworks group'),
        ),
    ]
