# Generated by Django 3.2.9 on 2021-11-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('student', '0005_auto_20211120_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.session'),
        ),
    ]
