# Generated by Django 3.2.9 on 2021-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211213_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='homeworks',
            field=models.ManyToManyField(blank=True, to='student.HomeWork', verbose_name='Student homeworks group'),
        ),
    ]
