# Generated by Django 3.2.9 on 2021-12-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentgroup_homeworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='homeworks',
        ),
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ManyToManyField(blank=True, to='student.StudentGroup', verbose_name='Student homeworks group'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.Student', verbose_name='Student homeworks'),
        ),
    ]
