# Generated by Django 3.2.9 on 2021-12-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_remove_module_evaluation'),
        ('student', '0008_auto_20211213_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.evaluation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='module',
            field=models.ManyToManyField(blank=True, to='module.Module'),
        ),
    ]
