# Generated by Django 3.2.9 on 2021-12-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20211213_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='students',
            new_name='student',
        ),
    ]
