# Generated by Django 3.2.9 on 2021-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_homework_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lien_github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
