# Generated by Django 3.2.9 on 2021-12-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_homework_lien_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='module',
        ),
    ]
