# Generated by Django 3.2.9 on 2021-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_student_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='group',
        ),
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup', verbose_name='Student homeworks group'),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Student homeworks'),
        ),
    ]
