# Generated by Django 3.2.9 on 2021-12-15 13:11

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20211215_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='order',
            field=models.FileField(blank=True, null=True, upload_to=student.models.file_path),
        ),
    ]
