# Generated by Django 3.2.9 on 2021-12-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20211215_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Absent Student'),
        ),
    ]
