# Generated by Django 3.2.9 on 2021-12-16 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_remove_module_teacher'),
        ('student', '0019_alter_homework_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.evaluation'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup', verbose_name='Student homeworks group'),
        ),
    ]
