# Generated by Django 3.2.9 on 2021-12-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20211216_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='absence',
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Absent Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup'),
        ),
    ]
