# Generated by Django 3.2.9 on 2021-12-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20211216_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentgroup'),
        ),
    ]
