# Generated by Django 3.2.9 on 2021-12-17 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_session_module'),
        ('student', '0026_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.session', verbose_name='Absent Session'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Absent Student'),
        ),
    ]
