# Generated by Django 3.2.9 on 2021-12-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_evaluation_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='teacher',
        ),
    ]
