# Generated by Django 3.2.9 on 2021-12-17 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_remove_module_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
    ]
